In [1]:
import os 
os.environ['KERAS_BACKEND'] = 'theano'

In [2]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')



Using Theano backend.


In [ ]:
# Loading the cascades
face_cascade = cv2.CascadeClassifier('D:\Data scientist\Dataset\Object_detection\haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='Bhavesh'
        elif(pred[0][0]>0.5):
            name='Aparajita'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[5.031867e-23 1.000000e+00]]
[[3.5562918e-12 1.0000000e+00]]
[[0.99703985 0.00296014]]
[[1.0000000e+00 1.5849187e-15]]
[[1.0000000e+00 5.4343276e-11]]
[[9.9997497e-01 2.5017043e-05]]
[[8.376556e-04 9.991623e-01]]
[[9.9996859e-01 3.1386102e-05]]
[[1.000000e+00 4.429962e-13]]
[[1.1624419e-10 1.0000000e+00]]
[[1.2096413e-28 1.0000000e+00]]
[[8.7e-44 1.0e+00]]
[[0.32415214 0.6758479 ]]
[[1.9080947e-18 1.0000000e+00]]
[[1.4635665e-08 1.0000000e+00]]
[[1.7661323e-27 1.0000000e+00]]
[[5.308543e-11 1.000000e+00]]
[[1.2134344e-15 1.0000000e+00]]
[[4.528584e-17 1.000000e+00]]
[[1.4836716e-15 1.0000000e+00]]
[[3.919334e-21 1.000000e+00]]
[[1.1099799e-33 1.0000000e+00]]
[[1.000000e+00 2.347585e-35]]
[[9.9981427e-01 1.8571454e-04]]
[[0.0595683 0.9404317]]
[[5.642954e-04 9.994357e-01]]
[[2.1999846e-11 1.0000000e+00]]
[[0.9885414  0.01145858]]
[[2.9409339e-16 1.0000000e+00]]
[[1.6940911e-13 1.0000000e+00]]
[[0.00284394 0.9971561 ]]
[[1.080393e-28 1.000000e+00]]
[[1.0e+00 1.4e-44]]
[[1. 0.]]
[[1.0000

[[1. 0.]]
[[1. 0.]]
[[0.99776626 0.00223377]]
[[1. 0.]]
[[1.00e+00 4.93e-43]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.e+00 1.e-45]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1.00e+00 1.72e-43]]
[[1. 0.]]
[[1.0000000e+00 3.5767253e-24]]
[[1.0000000e+00 2.7080295e-08]]
[[8.7236685e-07 9.9999911e-01]]
[[7.708223e-19 1.000000e+00]]
[[1.129342e-23 1.000000e+00]]
[[1.1257129e-21 1.0000000e+00]]
[[1.5250391e-11 1.0000000e+00]]
[[4.199683e-15 1.000000e+00]]
[[1.4326886e-14 1.0000000e+00]]
[[9.999832e-01 1.681983e-05]]
[[8.564545e-33 1.000000e+00]]
[[9.9962795e-01 3.7205944e-04]]
[[1.000000e+00 9.049925e-12]]
[[9.9999034e-01 9.6716230e-06]]
[[1.000000e+00 3.305076e-26]]
[[1.0e+00 2.8e-44]]
[[1.0000000e+00 6.2125464e-33]]
[[1.000000e+00 4.347008e-27]]
[[1. 0.]]
[[1.000000e+00 8.569556e-23]]
[[1.000000e+00 5.888394e-38]]
[[1.00e+00 4.02e-43]]
[[1.00000e+00 5.86602e-40]]
[[1. 0.]]
[[1. 0.]]
[[1.000000e+00 1.869713e-39]]
[[1. 0.]]
[[1.0000000e+00 1.1958837e-32]]
[[1. 0.]]
[[1. 0.]]
[[1.00000000e+00 1.479

[[1.000000e+00 8.947384e-21]]
[[1.0000000e+00 2.4681698e-22]]
[[1.0000000e+00 1.3594485e-08]]
[[1.000000e+00 6.637311e-13]]
[[1.0000000e+00 5.0717768e-12]]
[[1.5441535e-04 9.9984556e-01]]
[[1.3465183e-25 1.0000000e+00]]
[[2.1060246e-27 1.0000000e+00]]
[[0.9013408  0.09865923]]
[[5.9577135e-38 1.0000000e+00]]
[[1.3186913e-34 1.0000000e+00]]
[[1.850661e-16 1.000000e+00]]
[[1.000000e+00 6.386811e-33]]
[[3.4368712e-12 1.0000000e+00]]
[[1.0000000e+00 2.8723866e-34]]
[[5.318072e-25 1.000000e+00]]
[[1.8633244e-26 1.0000000e+00]]
[[8.091441e-19 1.000000e+00]]
[[1.0000000e+00 1.0357976e-37]]
[[1.0000000e+00 2.1597947e-35]]
[[1.0000000e+00 2.8736067e-09]]
[[1.0000000e+00 1.3328238e-08]]
[[1.0000000e+00 1.0854729e-08]]
[[1.0000000e+00 1.2901972e-15]]
[[1.0000000e+00 1.3971856e-10]]
[[9.999996e-01 3.885657e-07]]
[[0.02816112 0.9718389 ]]
[[9.999969e-01 3.100309e-06]]
[[0.9932071  0.00679291]]
[[6.458945e-17 1.000000e+00]]
[[2.0538254e-04 9.9979460e-01]]
[[1.0000000e+00 1.1572131e-16]]
[[1.000000e+